# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import RPi.GPIO as GPIO
import sys

GPIO.setmode(GPIO.BOARD)

# Define pins
LivingRoomPin = 11
BathroomPin = 13
ClosetPin = 15

GPIO.setup(LivingRoomPin, GPIO.OUT)
GPIO.setup(BathroomPin, GPIO.OUT)
GPIO.setup(ClosetPin, GPIO.OUT)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Title label
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(0, 20, 751, 101))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")

        # Body label
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(100, 250, 550, 120))
        font2 = QtGui.QFont()
        font2.setPointSize(20)
        self.label2.setFont(font2)
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")

        # Bathroom LED 
        self.Bathroom = QtWidgets.QRadioButton(self.centralwidget)
        self.Bathroom.setGeometry(QtCore.QRect(320, 210, 200, 50))
        font3 = QtGui.QFont()
        font3.setFamily("Segoe UI")
        font3.setPointSize(24)      
        font3.setWeight(75)
        self.Bathroom.setFont(font3)
        self.Bathroom.setObjectName("Bathroom")
        self.Bathroom.setAutoExclusive(False)
        
        # Closet LED 
        self.Closet = QtWidgets.QRadioButton(self.centralwidget)
        self.Closet.setGeometry(QtCore.QRect(560, 210, 200, 50))
        self.Closet.setFont(font3)
        self.Closet.setObjectName("Closet")
        self.Closet.setAutoExclusive(False)

        # Living Room LED 
        self.LivingRoom = QtWidgets.QRadioButton(self.centralwidget)
        self.LivingRoom.setGeometry(QtCore.QRect(50, 210, 200, 50))
        self.LivingRoom.setFont(font3)
        self.LivingRoom.setObjectName("LivingRoom")
        self.LivingRoom.setAutoExclusive(False)

        # Exit button
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(270, 470, 200, 41))
        self.exitButton.setFont(font2)
        self.exitButton.setObjectName("exitButton")
        self.exitButton.pressed.connect(self.turnLightsOff)
        self.exitButton.pressed.connect(MainWindow.close)

        # Create LED ON & OFF image labels
        self.blueOFF = QtWidgets.QLabel(self.centralwidget)
        self.blueOFF.setGeometry(QtCore.QRect(110, 270, 31, 51))
        self.blueOFF.setText("")
        self.blueOFF.setPixmap(QtGui.QPixmap("leds/blueLedOFF.png"))
        self.blueOFF.setScaledContents(True)
        self.blueOFF.setObjectName("blueOFF")

        self.greenOFF = QtWidgets.QLabel(self.centralwidget)
        self.greenOFF.setGeometry(QtCore.QRect(380, 270, 31, 51))
        self.greenOFF.setLineWidth(0)
        self.greenOFF.setText("")
        self.greenOFF.setPixmap(QtGui.QPixmap("leds/greenLedOFF.png"))
        self.greenOFF.setScaledContents(True)
        self.greenOFF.setObjectName("greenOFF")

        self.yellowOFF = QtWidgets.QLabel(self.centralwidget)
        self.yellowOFF.setGeometry(QtCore.QRect(600, 270, 31, 51))
        self.yellowOFF.setLineWidth(0)
        self.yellowOFF.setText("")
        self.yellowOFF.setPixmap(QtGui.QPixmap("leds/yellowLedOFF.png"))
        self.yellowOFF.setScaledContents(True)
        self.yellowOFF.setObjectName("yellowOFF")

        self.blueON = QtWidgets.QLabel(self.centralwidget)
        self.blueON.setGeometry(QtCore.QRect(100, 260, 51, 61))
        self.blueON.setText("")
        self.blueON.setPixmap(QtGui.QPixmap("leds/blueLedON.png"))
        self.blueON.setScaledContents(True)
        self.blueON.setObjectName("blueON")

        self.greenON = QtWidgets.QLabel(self.centralwidget)
        self.greenON.setGeometry(QtCore.QRect(370, 260, 51, 61))
        self.greenON.setText("")
        self.greenON.setPixmap(QtGui.QPixmap("leds/greenLedON.png"))
        self.greenON.setScaledContents(True)
        self.greenON.setObjectName("greenON")

        self.yellowON = QtWidgets.QLabel(self.centralwidget)
        self.yellowON.setGeometry(QtCore.QRect(590, 260, 51, 61))
        self.yellowON.setText("")
        self.yellowON.setPixmap(QtGui.QPixmap("leds/yellowLedON.png"))
        self.yellowON.setScaledContents(True)
        self.yellowON.setObjectName("yellowON")

        # Make sure the LED icon is always OFF to begin with
        self.blueON.hide()
        self.greenON.hide()
        self.yellowON.hide()

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Checks if the living room light is on/off and calls the lightToggled method accordingly
        self.LivingRoom.toggled.connect(lambda checked: self.lightToggled(self.LivingRoom, "Living Room", checked))
        self.Bathroom.toggled.connect(lambda checked: self.lightToggled(self.Bathroom, "Bathroom", checked))
        self.Closet.toggled.connect(lambda checked: self.lightToggled(self.Closet, "Closet", checked))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Linda\'s House Lights"))
        self.LivingRoom.setText(_translate("MainWindow", "Living Room"))
        self.Bathroom.setText(_translate("MainWindow", "Bathroom"))
        self.Closet.setText(_translate("MainWindow", "Closet"))
        self.exitButton.setText(_translate("MainWindow", "Exit GUI"))

    # Method which hides either the LED OFF/LED ON icon depending on the state of the LED
    def updateLedImage(self):
        # Update Living Room LED icon
        self.blueON.setVisible(self.LivingRoom.isChecked())
        self.blueOFF.setVisible(not self.LivingRoom.isChecked())

        # Update Bathroom LED icon
        self.greenON.setVisible(self.Bathroom.isChecked())
        self.greenOFF.setVisible(not self.Bathroom.isChecked())

        # Update Closet LED icon
        self.yellowON.setVisible(self.Closet.isChecked())
        self.yellowOFF.setVisible(not self.Closet.isChecked())

    # Method which sends a signal to Raspberry Pi device to turn on an LED and all others off (if already on)
    def lightToggled(self, checkedBtn, room, checked):
        # To use in for loop
        ledBtns = [self.LivingRoom, self.Bathroom, self.Closet]
        if checked:
            # Create a for loop which iterates through each light which hasnt been toggled on and blocks toggle signals to turn them off 
            for ledBtn in ledBtns:
                if ledBtn is not checkedBtn:
                    ledBtn.blockSignals(True)
                    ledBtn.setChecked(False)
                    ledBtn.blockSignals(False)
            
            # Calls method which turns lights off
            self.turnLightsOff()

            # Turns Living Room lights on
            if room == "Living Room":
                GPIO.output(LivingRoomPin, GPIO.HIGH)   # Sends signal to Raspberry Pi pin

            # Turns Bathroom lights on
            elif room == "Bathroom":
                GPIO.output(BathroomPin, GPIO.HIGH)

            # Turns Closet lights on
            elif room == "Closet":
                GPIO.output(ClosetPin, GPIO.HIGH)

            # Print ON message
            self.label2.setText(room + " Light ON")

        else:
            # Turn the room thats not checked OFF
            if room == "Living Room":
                GPIO.output(LivingRoomPin, GPIO.LOW)   # Sends signal to Raspberry Pi pin

            # Turns Bathroom lights on
            elif room == "Bathroom":
                GPIO.output(BathroomPin, GPIO.LOW)

            # Turns Closet lights on
            elif room == "Closet":
                GPIO.output(ClosetPin, GPIO.LOW)
            
            # Print OFF message
            self.label2.setText(room + " Light OFF")

        self.updateLedImage()

    # Method to turn all lights off
    def turnLightsOff(self):
        GPIO.output(LivingRoomPin, GPIO.LOW)
        GPIO.output(BathroomPin, GPIO.LOW)
        GPIO.output(ClosetPin, GPIO.LOW)

    def close(self):
        GPIO.cleanup()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
